version: '3'
services:
  db:
    container_name: 'NestTestDB'
    image: 'postgres'
    restart: 'always'
    environment:
      POSTGRES_USER: 'nest_test_user'
      POSTGRES_PASSWORD: 'n3st_t3st_us3r'
      POSTGRES_DB: 'nest_test'
    volumes: 
      - './data:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
  app:
    container_name: 'NestTestApp'
    build:
      context: './'
      dockerfile: './Dockerfile'
    env_file: './env/.production.env'
    environment: 
      - NODE_ENV=production
    restart: 'always'
    command: npm run start:prod
    links:
      - db
    depends_on:
      - db
    ports: 
      - '3000:3000'
